server:
  address: localhost
  port: 10000
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
ribbon:
  eureka:
    enabled: false