server:
  address: localhost
  port: 8080
spring:
  application:
    name: microservice-index
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: localhost
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
feign:
  hystrix:
    enabled: true