server:
  address: localhost
  port: 8002
spring:
  application:
    name: microservice-user
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauleZone: http://localhost:8761/eureka/
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true